### PR TITLE
Document auth.buch.de

### PR DESCRIPTION
**Pull request by AaronDewes**
Source: Own research, https://github.com/hzulla/tolino-python/commit/c655dbcd1b23e3874fd7dc78736570ac27ff5123

### CODE REVIEW

**Comment by AaronDewes** [comment]
[environments.zip](https://github.com/cweiske/tolino-api-docs/files/6728053/environments.zip)

And maybe you'll find some interesting APIs you don't know yet here, I'll try to document these later one, but it might take some time, you can have a look too. It seems like not all of them have been documented so far

**Comment by AaronDewes** [comment]
And are you also documenting internal URLs?

If yes, you might find this interesting:

```Java

    public static final String BROWSER_USER_AGENT = " BROWSER";
    public static final String OAUTH_USER_AGENT = (" DT_EINK_10_NETRONIX DT_EINK_UPD_PP_" + Globals.getApplicationVersionName());
    public static final String SHOP_HEADER_ACCESS_TOKEN = "X-Access-Token";
    public static final String SHOP_HEADER_FORCE_LOGIN = "X-Force-Auth";
    public static final String SHOP_HEADER_VISUAL_AID_MODE = "VIMS";
    public static final String SHOP_USER_AGENT = " READER";
    public static final String URL_CLOSE_SHOP = "epublishing://closeshop";
    public static final String URL_GET_PARAM_DELIVERABLE_ID = "deliverableid";
    public static final String URL_GET_PARAM_EXTRACT_COVER_URL = "extractcoverurl";
    public static final String URL_GET_PARAM_EXTRACT_DELIVERABLE_ID = "extractdeliverableid";
    public static final String URL_GET_PARAM_EXTRACT_DOWNLOAD_URL = "extractdownloadurl";
    public static final String URL_GET_PARAM_EXTRACT_PURCHASE_URL = "extractpurchaseurl";
    public static final String URL_GET_PARAM_LOGIN_FAIL_URL = "loginfailureurl";
    public static final String URL_GET_PARAM_OAUTH_KEY_CODE = "code";
    public static final String URL_GET_PARAM_OAUTH_KEY_ERROR = "error";
    public static final String URL_GET_PARAM_OAUTH_VALUE_ERROR_SERVER = "server_error";
    public static final String URL_GET_PARAM_SEARCH_REQUEST = "q";
    public static final String URL_GET_PARAM_TARGET_URL = "targeturl";
    public static final String URL_HANDSHAKE_CANCEL = "epublishing://handshakeCancel";
    public static final String URL_HANDSHAKE_LIB_JUMP = "epublishing://handshakeFinish";
    public static final String URL_OAUTH_LOGIN_REDIRECT = "epublishing://login";
    public static final String URL_OPEN_BOOK = "epublishing://openbook";
    public static final String URL_OPEN_EXTRACT = "epublishing://openextract";
    public static final String URL_OPEN_LIBRARY = "epublishing://library";
    public static final String URL_OPEN_LOGIN = "epublishing://requestauth";
    public static final String URL_OPEN_SEARCH = "epublishing://search";
    public static final String URL_OPEN_SEARCH_RESULT = "epublishing://opensearchresult";
    public static final String URL_PREFIX = "epublishing://";
    public static final String URL_RESELLER_CHANGE_CANCEL = "epublishing://resellerCancel";
    public static final String URL_RESELLER_CHANGE_FINISH_AND_RESET = "epublishing://resellerChangeFinishFactoryReset";
```

**Comment by cweiske** [comment]
Documenting the tolino-internal urls is a good idea.

**Comment by AaronDewes** [comment]
I got a partial decompilation, partial rewrite of the Tolino firmware in a private repo, I can give you access to it if you're interested.

**Comment by cweiske** [comment]
No, not right now.
My goal is to have a replacement server that works with unmodified tolinos.

**Comment by AaronDewes** [comment]
Yeah, that's why I thought you might want to know exactly what the Tolino needs/expects

**Comment by cweiske** [comment]
Thanks, merged.

**Pull request merged**
